---
- name: Install packages
  hosts: all
  tasks:
    - name: Install packages
      apt:
        name: 
        
          - gcc
          
          - make
          
          - build-essential
          
          - libpam0g-dev
          
          - libssl-dev
          
          - libaudit-dev
          
          - wget
          
        state: present
        update_cache: yes

    - name: Downoload Source code
      get_url:
        url: http://www.sudo.ws/dist/sudo-1.8.23.tar.gz
        dest: /tmp/sudo-1.8.23.tar.gz
        mode: '0644'
        
    - name: Extract source code
      unarchive:
        src: /tmp/sudo-1.8.23.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Compile and install package
      shell: './configure --prefix=/usr --libexecdir=/usr/lib --with-secure-path --with-all-insults --with-env-editor --docdir=/usr/share/doc/sudo-1.8.23 --with-passprompt="[sudo] password for %p: " && make && make install && ln -sfv libsudo_util.so.0.0.0 /usr/lib/sudo/libsudo_util.so.0'
      args:
       chdir: /tmp/sudo-1.8.23

    - name: Upload cfg file
      copy:
        src: /home/etc
        dest: home/etc

    - name: Start service sudo-1.8.23
      command: /home/etc

    - name: Add to Start sudo-1.8.23
      cron:
        name: sudo-1.8.23
        special_time: reboot
        job: /home/etc
