---
- name: Install packages
  hosts: all
  tasks:
    - name: Install packages
      apt:
        name: 
        
          - htop
          
          - nginx
          
          - apache2
          
        state: present
        update_cache: yes
