- name: Install and configure Apache web server
  hosts: debsrv10
  become: yes

  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present
      

    - name: Ensure Apache is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

