- hosts: debsrv1
  become: yes
  tasks:
    - name: Install build dependencies
      apt:
        name: 
          - build-essential
          - libacl1-dev
          - libattr1-dev
          - libblkid-dev
          - libreadline-dev
          - python2
          - python2-dev
          - gdb
          - pkg-config
          - libpopt-dev
          - libldap2-dev
          - dnsutils
          - libbsd-dev
          - krb5-user
          - docbook-xsl
          - xsltproc
          - libgnutls28-dev
          - libtirpc-dev
          - libssl-dev
        state: present
        update_cache: yes

    - name: Download Samba 4.6.0 source code
      get_url:
        url: https://download.samba.org/pub/samba/stable/samba-4.6.0.tar.gz
        dest: /tmp/samba-4.6.0.tar.gz

    - name: Extract Samba source code
      unarchive:
        src: /tmp/samba-4.6.0.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Compile and install Samba
      shell: ./configure --without-ldap --without-ad-dc --disable-python && make && make install
      args:
        chdir: /tmp/samba-4.6.0
        executable: /bin/bash
        creates: /usr/local/samba/sbin/smbd
