- hosts: debsrv24
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name: 
          - gcc
          - libacl1-dev
          - libblkid-dev
          - libreadline-dev
          - gdb
          - python-dev
          - pkg-config
          - libpopt-dev
          - libldap2-dev
          - dnsutils
          - libattr1-dev
          - make
        state: present
        update_cache: yes

    - name: Download Samba source code
      get_url:
        url: https://download.samba.org/pub/samba/stable/samba-4.6.0.tar.gz
        dest: /tmp/samba-4.6.0.tar.gz

    - name: Extract Samba source code
      unarchive:
        src: /tmp/samba-4.6.0.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Compile and install Samba
      shell: "./configure --prefix=/usr/local/samba --without-ldap --without-ad-dc --without-ads --without-pam && make && make install"
      args:
        chdir: /tmp/samba-4.6.0

    - name: Create Samba configuration
      copy:
        dest: /usr/local/samba/etc/smb.conf
        content: |
          [global]
          nt pipe support = yes
          [public]
          public = yes
          path = /tmp
          writable = yes
          guest ok = yes
      tags: createsmbcfg

    - name: Start Samba
      command: /usr/local/samba/sbin/smbd
      tags: startsmbd

    - name: Create Samba Service File
      shell: |
        cp /usr/local/samba/sbin/smbd /etc/init.d/smbd
        chmod +x /etc/init.d/smbd
      tags:
        - Create Samba Service File

    - name: Enable Samba on boot
      systemd:
        name: smbd
        enabled: yes
