- hosts: debsrv1
  become: yes
  tasks:
    - name: Install build dependencies
      apt:
        name:
          - build-essential
          - zlib1g-dev
          - libncurses5-dev
          - libgdbm-dev
          - libnss3-dev
          - libssl-dev
          - libreadline-dev
          - libffi-dev
          - libbz2-dev
          - libblkid-dev
          - libpopt-dev
          - libacl1-dev
          - libldap2-dev
        state: present
        update_cache: yes

    - name: Download Python 2.7.18 source
      get_url:
        url: https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
        dest: /tmp/Python-2.7.18.tgz

    - name: Extract Python 2.7.18 source
      unarchive:
        src: /tmp/Python-2.7.18.tgz
        dest: /tmp/
        remote_src: yes

    - name: Compile and install Python 2.7.18
      shell: ./configure --enable-unicode=ucs4 && make && make altinstall
      args:
        chdir: /tmp/Python-2.7.18
        executable: /bin/bash
        creates: /usr/local/bin/python2.7

    - name: Download Samba 4.5.10 source code
      get_url:
        url: https://download.samba.org/pub/samba/stable/samba-4.5.10.tar.gz
        dest: /tmp/samba-4.5.10.tar.gz

    - name: Extract Samba source code
      unarchive:
        src: /tmp/samba-4.5.10.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Compile and install Samba
      shell: ./configure && make && make install
      args:
        chdir: /tmp/samba-4.5.10
        executable: /bin/bash
        creates: /usr/local/samba/sbin/smbd
