---
- hosts: debsrv1
  become: yes
  tasks:
    - name: Install build dependencies
      apt:
        name:
          - build-essential
          - zlib1g-dev
          - libncurses5-dev
          - libgdbm-dev
          - libnss3-dev
          - libssl-dev
          - libreadline-dev
          - libffi-dev
          - libbz2-dev
          - libblkid-dev
          - libpopt-dev
          - libacl1-dev
          - libldap2-dev
          - nettle-dev
          - libidn2-0-dev
        state: present
        update_cache: yes

    - name: Download GnuTLS source code
      get_url:
        url: https://www.gnupg.org/ftp/gcrypt/gnutls/v3.6/gnutls-3.6.15.tar.xz
        dest: /tmp/gnutls-3.6.15.tar.xz

    - name: Extract GnuTLS source code
      unarchive:
        src: /tmp/gnutls-3.6.15.tar.xz
        dest: /tmp/
        remote_src: yes

    - name: Compile and install GnuTLS
      shell: ./configure && make && make install
      args:
        chdir: /tmp/gnutls-3.6.15
        executable: /bin/bash

    - name: Set shared GnuTLS library path
      shell: echo '/usr/local/lib' > /etc/ld.so.conf.d/gnutls.conf && ldconfig
      args:
        executable: /bin/bash

    - name: Download Samba 4.5.10 source code
      get_url:
        url: https://download.samba.org/pub/samba/stable/samba-4.5.10.tar.gz
        dest: /tmp/samba-4.5.10.tar.gz

    - name: Extract Samba source code
      unarchive:
        src: /tmp/samba-4.5.10.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Compile and install Samba 4.5.10
      shell: ./configure && make && make install
      args:
        chdir: /tmp/samba-4.5.10
        executable: /bin/bash
        creates: /usr/local/samba/sbin/smbd
