- name: Create user
  vars:
  - passwrd: qq123456
  hosts: srvubu2
  tasks:
    - name: Create users
      become: yes
      user:
        name: User1
        #state: present
        shell: /bin/bash
        create_home: yes
        password: "{{ passwrd | password_hash('sha512') }}"
        state: present 


