- name: Create new user
  hosts: all
  become: yes
  vars:
    passdw: debik

  tasks:
    - name: Create user  debik
      user:
        name: debik
        password: "{{passdw | password_hash('sha512')}}"
        shell: /bin/bash
        create_home: yes
        state: present
