---
- name: Install and configure Samba
  hosts: all
  become: yes
  tasks:
    - name: Install Samba
      apt:
        name: samba
        state: present

    - name: Create shared directory
      file:
        path: /srv/samba/share
        state: directory
        mode: '0777'

    - name: Configure Samba share
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [share]
          path = /srv/samba/share
          browseable = yes
          read only = no
          guest ok = yes
        marker: ' '
    - name: Restart Samba service
      service:
        name: smbd
        state: restarted
        enabled: yes

    - name: Ensure Samba service is running
      service:
        name: nmbd
        state: started
        enabled: yes
