- hosts: debsrv1
  become: yes
  tasks:
    - name: Insecure SSH configuration - Enable SSH protocol 1
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Protocol'
        line: 'Protocol 1'
      #notify: restart sshd
      tags: ensshv1 

    - name: Аутентификация по пустому паролю
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitEmptyPasswords'
        line: 'PermitEmptyPasswords yes'
      tags: authzero

    - name: Аутентификация для root
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin yes'
      tags: authroot 

    - name: Создание пользователя с пустым паролем
      user:
        name: your_username
        password: ""
      tags: emptpassuser

    - name: Создание пользователя со слабым паролем
      user:
        name: User1
        #state: present
        shell: /bin/bash
        create_home: yes
        password: "{{ passwrd | password_hash('sha512') }}"
        state: present 
      tags: weakpass

    - name: Снятие ограничения по кол-во попыток аутентификации
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?MaxAuthTries'
        line: 'MaxAuthTries 150'
      tags: maxauthtries

    - name: 'Restart sshd'
      systemd:
        name: sshd
        state: restarted

